version: "3.7"


# 컨테이너. 
services:

  db:
    # Dockerfile이 있는 위치
    build: ./DB(db_server)
    # 내부에서 개방할 포트 : 외부에서 접근할 포트
    ports:
      - "9000:9000"

  api:
    build: ./BackEnd(api_server)
    ports:
     - "6000:6000"
     
  front:
    build: ./FrontEnd(webserver)
    ports:
      - "3000:3000"
      # ec2에서 포트 허용때. 3000만 허용하면. 외부에서 접근 불가능하다. 



  



# docker stop $(docker ps -aq); docker rm $(docker ps -aq); docker image prune -a